CKEDITOR.plugins.add("simage",{icons:"simage",allowedContent:"img[alt,!src,width,height,data-width,data-height]{border-style,border-width,float,height,margin‌​,margin-bottom,margi‌​n-left,margin-right,‌​margin-top,width}",init:function(f){f.addCommand("simage",{exec:function(d){a=document.createElement("input");a.setAttribute("type","file");a.setAttribute("accept",".jpg,.jpeg,.png,.tif,.gif,.svg");a.click();a.onchange=function(){file=a.files[0];$(CKEDITOR.currentInstance).trigger("enableFormSubmit");
curr=CKEDITOR.currentInstance;5E6<file.size?(b=document.createElement("div"),b.className="message alert alert-danger",m=document.createElement("span"),m.innerHTML="Image size exceeded! Please upload image of less than 5 MB.",b.appendChild(m),c=document.createElement("span"),c.className="close",c.innerHTML="X",b.appendChild(c),e=document.querySelector(".error-space"),e.appendChild(b),setTimeout(function(){alert=document.querySelector(".alert-danger");alert.parentNode.removeChild(alert)},2E4),c.onclick=
function(){b=document.querySelector(".alert-danger");b.parentNode.removeChild(b)},$(CKEDITOR.instances[curr.name]).trigger("enableFormSubmit")):-1==="jpeg jpg png svg gif tif svg+xml".split(" ").indexOf(file.type.split("/")[1])?(b=document.createElement("div"),b.className="message alert alert-danger",m=document.createElement("span"),m.innerHTML="The uploaded image format is not of acceptible format! Please upload an image!",b.appendChild(m),c=document.createElement("span"),c.className="close",c.innerHTML=
"X",b.appendChild(c),e=document.querySelector(".error-space"),e.appendChild(b),setTimeout(function(){alert=document.querySelector(".alert-danger");alert.parentNode.removeChild(alert)},2E4),c.onclick=function(){b=document.querySelector(".alert-danger");b.parentNode.removeChild(b)},$(CKEDITOR.instances[curr.name]).trigger("enableFormSubmit")):(img=new Image,img.onload=function(){inputWidth=this.width;inputHeight=this.height},img.src=window.URL.createObjectURL(file),formData=new FormData,formData.append("file",
file),loaderElem=new CKEDITOR.dom.element("loader-elem"),loaderHtmlStr='\x3cdiv style\x3d"position: relative; z-index: 100;width: 100%;height: 100%;text-align: center;background: white;opacity: 0.75;pointer-events:none"\x3e\x3cdiv style\x3d"width: 100%;height: 30px;margin-top: 100px;"\x3ePlease wait while image is uploading...\x3c/div\x3e\x3c/div\x3e',loaderDomEle=CKEDITOR.dom.element.createFromHtml(loaderHtmlStr),loaderElem.append(loaderDomEle),d.insertElement(loaderElem),CKEDITOR.currentInstance.setReadOnly(!0),
$.ajax({url:d.config.imageUploadURL,type:"POST",data:formData,processData:!1,contentType:!1}).success(function(f){return function(g,f,h){g=JSON.parse(g);200==h.status&&(CKEDITOR.instances[curr.name].setReadOnly(!1),url=d.config.dataParser(g),elem=new CKEDITOR.dom.element("elem"),maxWidth=Math.min(inputWidth,600),maxHeight=Math.min(inputHeight,600),maxWidth/maxHeight>inputWidth/inputHeight?(width=maxWidth*inputWidth/inputHeight,height=maxHeight):maxWidth/maxHeight<inputWidth/inputHeight?(width=maxWidth,
height=maxHeight*inputHeight/inputWidth):(width=maxWidth,height=maxHeight),newLine=CKEDITOR.dom.element.createFromHtml("\x3cp\x3e\x3cbr\x3e\x3c/p\x3e"),d.config.srcSet?(srcSet=d.config.srcSet(g),imgElem='\x3cimg src\x3d"'+url+'" class\x3d"image-editor" srcset\x3d"'+srcSet+'" data-width\x3d"'+inputWidth+'" data-height\x3d"'+inputHeight+'" height\x3d"'+height+'" width\x3d"'+width+'"\x3e'):imgElem='\x3cimg src\x3d"'+url+'" class\x3d"image-editor" data-width\x3d"'+inputWidth+'" data-height\x3d"'+inputHeight+
'" height\x3d"'+height+'" width\x3d"'+width+'"\x3e',imgDomElem=CKEDITOR.dom.element.createFromHtml(imgElem),elem.append(imgDomElem),d.insertElement(newLine),d.insertElement(elem),d.insertElement(newLine),loaderElem.remove(),$(CKEDITOR.instances[curr.name]).trigger("enableFormSubmit"))}}(this)).error(function(d){return function(d,f,h){CKEDITOR.instances[curr.name].setReadOnly(!1);b=document.createElement("div");b.className="message alert alert-danger";m=document.createElement("span");m.innerHTML="Image upload failed! Please try again!";
b.appendChild(m);c=document.createElement("span");c.className="close";c.innerHTML="X";b.appendChild(c);e=document.querySelector(".error-space");e.appendChild(b);loaderElem.remove();$(CKEDITOR.instances[curr.name]).trigger("enableFormSubmit");setTimeout(function(){alert=document.querySelector(".alert-danger");alert.parentNode.removeChild(alert)},2E4);c.onclick=function(){b=document.querySelector(".alert-danger");b.parentNode.removeChild(b)}}}(this)))}}});f.ui.addButton("SImage",{label:"Custom Image Uploader",
command:"simage",toolbar:"insert"})}});